// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"agent/app/user/service/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	LoginReq          = user.LoginReq
	LoginResp         = user.LoginResp
	LogoutReq         = user.LogoutReq
	LogoutResp        = user.LogoutResp
	ProfileViewReq    = user.ProfileViewReq
	ProfileViewResp   = user.ProfileViewResp
	Profile           = user.Profile
	RegReq            = user.RegReq
	ProfileUpdateReq  = user.ProfileUpdateReq
	ProfileUpdateResp = user.ProfileUpdateResp
	RegResp           = user.RegResp

	User interface {
		Reg(ctx context.Context, in *RegReq) (*RegResp, error)
		Login(ctx context.Context, in *LoginReq) (*LoginResp, error)
		Logout(ctx context.Context, in *LogoutReq) (*LogoutResp, error)
		ProfileView(ctx context.Context, in *ProfileViewReq) (*ProfileViewResp, error)
		ProfileUpdate(ctx context.Context, in *ProfileUpdateReq) (*ProfileUpdateResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Reg(ctx context.Context, in *RegReq) (*RegResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Reg(ctx, in)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginReq) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in)
}

func (m *defaultUser) Logout(ctx context.Context, in *LogoutReq) (*LogoutResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Logout(ctx, in)
}

func (m *defaultUser) ProfileView(ctx context.Context, in *ProfileViewReq) (*ProfileViewResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ProfileView(ctx, in)
}

func (m *defaultUser) ProfileUpdate(ctx context.Context, in *ProfileUpdateReq) (*ProfileUpdateResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ProfileUpdate(ctx, in)
}
